services:
  bot:
    image: cybersec-bot
    build: .
    container_name: cybersec-bot
    restart: unless-stopped
    env_file:
      - .env  # Docker-compose сам подтянет ключи из локального .env
    volumes:
      # Монтируем именованный том в папку /app/data внутри контейнера.
      # Все данные, записанные в /app/data, теперь будут храниться в томе CyberSec_Vol.
      - CyberSec_Vol:/app/data

volumes:
  CyberSec_Vol:
    external: true # Указываем, что том создан вручную (docker volume create CyberSec_Vol)